== 소개

무엇보다 먼저: Starling 커뮤니티에 오신 것을 환영합니다!
2011년 첫 출시 이후 전세계의 개발자들은 작은 빨간 새(Starling 캐릭터)의 도움을 받아 놀라운 게임과 앱을 만들었습니다.
우리와 함께해줘서 고마워요!

잘 오셨습니다: 이 안내서는 당신이 알아야 할 모든 것을 가르쳐 줄 것입니다.
우리는 Asset Management와 같은 'A'에서 Zen 코딩과 같은 'Z'까지 모든 것을 다룰 것입니다.

프레임워크에 대한 느낌을 알 수 있도록 처음엔 간단한 게임부터 시작하겠습니다.
그런 다음 디스플레이 리스트 아키텍처 및 Starling의 애니메이션 시스템을 비롯하여 모든 개념을 자세하게 살펴보겠습니다.
마지막 챕터에는 맞춤형 렌더링 코드를 작성하는 방법과 같은 고급 Starling 사용자를위한 정보가 포함되어 있습니다.
당신이 그것을 알기 전에 당신은 스탈링의 마스터가 될 것입니다!

그러나 ActionScript 3.0 (AS3)을 기본적으로 이해해야 한다는 작은 전제 조건은 있습니다.
두려워하지 마세요: 다른 객체 지향 언어를 사용했다면 빠르게 이해할 수 있고, 여러 책과 자습서가 있습니다.

특별히 한 권의 책을 원한다면 콜린 무크의 "Essential ActionScript 3"을 권할 수 있습니다.
내가 AS3를 시작했을 때 그것은 중요한 모든 너트와 볼트를 가르쳐 주었고, 나는 여전히 그것을 책꽂이에서 수시로 꺼내고 있습니다.
(특히 AS3의 XML 처리를 위한 이상한 E4X 구문).

.AS3와 JS 비교
****
ActionScript 3이 실제로 JavaScript의 후계자가 되도록 설계되었다는 것을 알고 계셨습니까?
아시다시피 JavaScript는 ECMAScript 언어 사양을 구현한 것입니다.
ActionScript 3는 ECMAScript 4를 기반으로 합니다.
그러나 대부분 정치적인 이유로 인해 ECMAScript 4는 버려졌으며 브라우저에서 사용되지 않았습니다.
오늘날, ActionScript 3는 그 표준의 유일한 구현으로 남아 있습니다.
그러나 역설적이게도 최신 버전의 JavaScript는 ActionScript 3처럼 보입니다.
****
