== 리소스(Resources)

우리는 지금 거의 모든 빌딩을 위한 블록들을 갖추고 있습니다.
우리가 마침내 첫 번째 프로젝트를 시작할 수 있도록 모든 것을 설정하는 방법을 살펴 보겠습니다.

=== AIR SDK

IDE를 선택하여 설치한 경우 다음 단계는 최신 버전의 AIR SDK를 다운로드하는 것입니다.
Adobe는 3개월마다 한 번씩 새로운 안정 버전을 출시하므로 최신 버전을 유지하십시오!
새로운 각 릴리스에는 일반적으로 최신 모바일 운영 체제와의 호환성을 유지하는 데 중요한 몇 가지 중요한 버그 수정이 포함되어 있습니다.
또한 새로운 기능을 실험하는 팀을 지속적으로 보게 될 것이며 Starling에서 그 페이스를 따라 잡기 위해 열심히 노력하고 있습니다.

최신 릴리스는 항상 여기에서 찾을 수 있습니다:
https://www.adobe.com/devnet/air/air-sdk-download.html[Download Adobe AIR SDK]

노트: Starling 2는 최소한 AIR 19를 필요로 합니다.

=== Flash Player Projector

프로젝트가 Flash Player에서 실행되기를 원한다면 Projector라는 독립 실행 형 버전 (Debug 및 Release 버전으로 사용 가능)을 얻는 것이 좋습니다.
프로젝터의 장점은 훨씬 쉬운 디버깅 경험입니다.
예를 들어 브라우저를 통해 디버그 할 수도 있습니다 (플러그인의 디버그 버전을 설치 한 후).
하지만 (개인적인 생각이지만) 그것은 매우 귀찮습니다.
프로젝터는 훨씬 빨리 시작되므로 HTML 파일을 구성 할 필요가 없습니다.

이 페이지에는 개발자에게 적합한 모든 Flash Player 버전의 목록이 포함되어 있습니다. "projector content debugger, 프로젝터 컨텐츠 디버거"를 찾으십시오:
https://www.adobe.com/support/flashplayer/debug_downloads.html[Adobe Flash Player Debug Downloads]

노트: 다시 말하지만, IDE가 올바른 플레이어를 찾는 방법을 알아야 할 수도 있습니다. 예를 들어 IDEA는 이 설정이 디버그 구성의 일부입니다.

다시 말하지만, IDE가 올바른 플레이어를 찾는 방법을 알아야 할 수도 있습니다.
예를 들어 IDEA에서 이 설정은 디버그 구성 화면의 일부입니다.
다른 IDE는 단순히 시스템 기본값을 사용할 수 있습니다.
어쨌든 항상 SWF를 컴파일한 AIR SDK 버전 이상의 플레이어 버전을 사용하는 것이 중요합니다.

=== Starling

이제 남은건 Starling 뿐입니다.
두 가지 방법 중 하나를 선택할 수 있습니다.

a. 최신 릴리스를에서 zip 파일로 다운로드하십시오. http://gamua.com/starling/download/[gamua.com/starling/download].
b. Starling의 Git 저장소를 복제하십시오.

전자의 장점은 프로젝트에 쉽게 링크되는 미리 컴파일 된 SWC 파일 (starling / bin 폴더에 있음)이 함께 제공된다는 것입니다.
그러나 항상 안정(stable) 버전만 얻을 수 있습니다.
즉, 최신 최신 업데이트 및 수정 사항을 놓치고 있습니다! 이런 이유로 나는 오히려 Git을 사용하길 권장합니다.

팁: 버그를 보고하고 며칠 후 해결한다고 가정해 봅시다. (네, 그런 일도 있습니다!)
표준 다운로드로 새로운 stable 릴리스를 만들 때까지 기다려야 합니다.
하지만, Git repository를 사용하는 경우 바로 해결할 수 있습니다.

Git에 대해 깊이있게 살펴보면 이 매뉴얼의 범위를 벗어나지만 웹에서 많은 튜토리얼을 찾을 수 있습니다. Git을 설치하면 다음 명령을 사용하여 전체 Starling 저장소를 디스크에 복제(Clone)할 수 있습니다:

  git clone https://github.com/Gamua/Starling-Framework.git

그러면 Starling이 'Starling-Framework' 폴더로 복사됩니다.
'starling/src' 하위 폴더에서 실제 소스 코드를 찾습니다.
언급된 모든 IDE는 이 폴더를 프로젝트에 대한 소스 경로로 추가하는 것을 지원합니다.
SWC 파일에 연결하는 것보다 더 이상 복잡하지 않습니다.
깔끔한 부작용으로 Starling의 소스를 디버깅 할 수 있습니다.

그러나 이 방법에 가장 적합한 이유는 Starling을 최신 버전으로 업데이트하는 것에 대한 것입니다.
저장소의 디렉토리로 이동하여 다음과 같이 하세요:

  cd Starling-Framework
  git pull

브라우저를 열고 수동으로 새 버전을 다운로드하는 것보다 훨씬 간단합니다. 그렇지 않습니까?

[노트]
====
고급 Git 사용자를 위한 몇 가지 추가 정보:

* Starling의 모든 일상적인 개발은 `master` 브랜치에서 발생합니다.
* 안정적인 릴리스는 태그가 붙습니다. (`v2.0`, `v2.0.1`, `v2.1`와 같이).
* 각 태그는 GitHub의 Release로 표시되어 있습니다. 그 시간에 미리 컴파일된 SWC 파일을 첨부할 것입니다.
====

=== 도움 얻기

우리 중 최고는 때때로 붙어 있습니다.
Starling의 버그로 인해 로드 블록을 치거나 해결할 수 없는 문제가 발생할 수 있습니다.
어느 쪽이든 Starling 공동체는 당신을 불행에 빠뜨리지 않습니다!
도움이 필요할 때 갈 수있는 몇 가지 리소스가 있습니다.

Starling 포럼::
그는 Starling 커뮤니티의 주요 허브입니다.
수십개의 새로운 게시물, 그것은 이전에 질문했던 문제들일 것입니다.
그래서 반드시 검색(Search) 기능을 사용하세요.
만약 도움이 되지 않는다면, 계정을 등록하여 질문해 주시기 바랍니다.
당신은 웹상에서 가장 친절 하고 인내심 많은 커뮤니티 중 하나를 볼 수 있을 것입니다! +
-> http://forum.starling-framework.org

Starling 매뉴얼::
ifdef::target-manual[지금 읽고 있는 온라인 설명서입니다.]
ifndef::target-manual[온라인 매뉴얼은 Starling을 광범위하게 소개합니다.]
난 최신 릴리즈를 유지하려고 노력할 것입니다. +
-> http://manual.starling-framework.org

Starling 위키::
링크와 다른 Starling에 대한 기사를 포함하는 위키 관련 항목, 그리고 가장 중요 한 것은: Starling 확장의 목록입니다. 우리는 나중에 그 중 일부를 설명합니다. +
-> http://wiki.starling-framework.org

API 레퍼런스::
모든 클래스와 메소드에 대한 자세한 내용은 Starling API 참조하는 것을 잊지 마세요. +
-> http://doc.starling-framework.org

Gamua 블로그::
Gamua 블로그를 통해 Starling에 대한 최신 뉴스와 상태를 확인하세요.
나는 조금 게으른 블로그 관리자입니다. 항상 각 Starling 릴리스에 대 한 하나 이상의 경우 인정 합니다. +
-> http://gamua.com/blog

트위터(Twitter)::
나에게 연락하는 가장 좋은 방법은 '@Gamua'를 통해 소셜 서비스를 이용하는 것입니다.
이 계정을 팔로우하세요. 최신 소식을 전해 드립니다. +
-> https://twitter.com/Gamua

