== 리소스(Resources)

우리는 지금 거의 모든 빌딩을 위한 블록들을 갖추고 있습니다.
우리가 마침내 첫 번째 프로젝트를 시작할 수 있도록 모든 것을 설정하는 방법을 살펴 보겠습니다.

=== AIR SDK

IDE를 선택하여 설치한 경우 다음 단계는 최신 버전의 _AIR SDK_를 다운로드하는 것입니다.
Adobe는 3개월마다 한 번씩 새로운 안정 버전을 출시하므로 최신 버전을 유지하십시오!
새로운 각 릴리스에는 일반적으로 최신 모바일 운영 체제와의 호환성을 유지하는 데 중요한 몇 가지 중요한 버그 수정이 포함되어 있습니다.
또한 새로운 기능을 실험하는 팀을 지속적으로 보게 될 것이며 Starling에서 그 페이스를 따라 잡기 위해 열심히 노력하고 있습니다.

최신 릴리스는 항상 여기에서 찾을 수 있습니다:
https://www.adobe.com/devnet/air/air-sdk-download.html[Download Adobe AIR SDK]

노트: Starling 2는 최소한 AIR 19를 필요로 합니다.

=== Flash Player Projector

If your project also aims to run in the _Flash Player_, I recommend you get the standalone version of it, called _Projector_ (available as _Debug_ and _Release_ versions).
The advantage of the projector is a much easier debugging experience.
Yes, you could also debug via the browser (after installing the debug-version of the plug-in) -- but personally, I find that extremely cumbersome.
The projector starts up much faster, and you don't need to configure any HTML files to get it going.

This page contains a list of all Flash Player versions suitable for developers. Look for the "projector content debugger":
https://www.adobe.com/support/flashplayer/debug_downloads.html[Adobe Flash Player Debug Downloads]

NOTE: The debugger is significantly slower than the standard version. Keep that in mind when you're working on performance optimization.

Again, your IDE might need to know how to find the correct player.
For example, in _IDEA_, this setting is part of the debug configurations screen; other IDEs might simply use the system default.
In any case, it's important to always use a player version that's equal to or higher than the AIR SDK version you compiled the SWF with.

=== Starling

Now all that's left to download is Starling itself.
You can choose between two ways of doing that.

a. Download the latest release as a zip-file from http://gamua.com/starling/download/[gamua.com/starling/download].
b. Clone Starling's _Git_ repository.

The advantage of the former is that it comes with a precompiled SWC file (found in the folder `starling/bin`) that is easily linked to your project.
However, you'll always only get the stable releases this way, which means you're missing out on the latest hot updates and fixes!
For this reason, I'd rather advocate using _Git_.

TIP: Let's say you report a bug and it is fixed a few days later (yes, that happens!): with the standard download, you'll have to wait for the fix until I'm creating a new stable release, which could be quite a while.
When you're using the _Git_ repository, you'll have the fix right away.

Going into depths about _Git_ would exceed the scope of this manual, but you'll find lots of great tutorials about it on the web.
Once installed, _Git_ can _clone_ the complete Starling repository to your disk with the following command:

  git clone https://github.com/Gamua/Starling-Framework.git

This will copy Starling to the folder `Starling-Framework`.
Look for the actual source code inside the sub-folder `starling/src`.
All of the mentioned IDEs support adding this folder as a _source path_ to your project, which will make Starling part of your project.
That's not any more complicated than linking to the SWC file; and as a neat side effect, you will even be able to step into Starling's source on debugging.

But what's best about this approach is how easy it is to update Starling to the latest version.
Simply navigate into the repository's directory and `pull`:

  cd Starling-Framework
  git pull

That's much simpler than opening up the browser and manually downloading a new version, isn't it?

[NOTE]
====
Some additional information for advanced _Git_-users:

* All day-to-day development in Starling happens on the `master` branch.
* Stable releases are _tagged_ (like `v2.0`, `v2.0.1`, `v2.1`).
* Each tag is marked as a _Release_ on _GitHub_, at which time I'll also attach a precompiled SWC file.
====

=== Getting Help

The best of us get stuck sometimes.
You might hit a road block because of a bug in Starling, or maybe because of a problem that seems impossible to solve.
Either way, the Starling community won't leave you alone in your misery!
Here are some resources that you can go to when you need help.

Starling Forum::
That's the main hub of the Starling community.
With dozens of new posts each day, it's very likely that your problem has already been asked before, so be sure to make use of the _search_ feature.
If that doesn't help, feel free to register an account and ask away.
One of the most friendly and patient communities you'll find on the web! +
-> http://forum.starling-framework.org

Starling Manual::
ifdef::target-manual[The online manual you are reading right now.]
ifndef::target-manual[The online manual provides an extensive introduction to Starling.]
I try my best to keep it updated for each new release. +
-> http://manual.starling-framework.org

Starling Wiki::
The wiki contains links and articles about different Starling related topics, and most importantly: a list of Starling extensions.
We will discuss some of those later. +
-> http://wiki.starling-framework.org

API Reference::
Don't forget to consult the Starling API Reference for detailed information about all classes and methods. +
-> http://doc.starling-framework.org

Gamua Blog::
Keep up to date with the latest news about Starling via the Gamua blog.
I must admit I'm a little lazy when it comes to writing blog posts, but there will always be at least one for each Starling release. +
-> http://gamua.com/blog

Twitter::
I'm using several social networks, but the best way to reach me is via `@Gamua`.
Follow this account to get updates about new developments or links to other Starling-powered games. +
-> https://twitter.com/Gamua

