== Adobe AIR는 무엇입니까?
ifndef::imagesdir[:imagesdir: ../../img]

불과 몇 년 전만 해도, Adobe의 Flash Player는 웹을 이용할 때 어디에나 있었습니다.
그 당시에는 기본적으로 웹용 인터렉티브 또는 애니메이션 콘텐츠를 만들려는 유일한 선택이었습니다.
브라우저는 비디오 사운드 및 애니메이션과 관련하여 매우 제한적인 기능을 가지고 있었고, 그들이 가진 몇 가지 기능은 브라우저 비 호환성으로 인해 어려움을 겪었습니다.
간단히 말해: 그것은 엉망이었죠.

그래서 Adobe Flash가 인기가 있었습니다.
footnote:[Flash는 원래 2005년 Adobe에서 인수한 Macromedia에 의해 만들어졌습니다.]
디자이너와 개발자는 직관적인 제작 프로그램을 이용해 멀티미디어 컨텐츠를 제작할 수 있었습니다. (지금은 Adobe Animate라 불립니다)
그렇게 하면, 모든 플랫폼에서 동일하게 보였습니다.
배우기 쉽고 강력한 언어인 ActionScript 3도 있고요.

플랫폼의 인기를 기반으로 Adobe는 브라우저 외부에서 실행되는 독립 실행 형 응용 프로그램에 동일한 기술을 사용하자고 인식했습니다.
그것이 바로 Adobe AIR 런타임 입니다.
AIR SDK로 작성된 응용 프로그램은 데스크톱 (Windows, macOS) 또는 모바일 (Android, iOS)에서 실행되는 독립 실행 형 응용 프로그램으로 배포될 수 있습니다.
표준 라이브러리는 플래시의 상위 라이브러리입니다, 그러므로 여러분은 Flash에서 할 수있는 모든 것을 AIR에서 할 수 있습니다; 게다가 파일 시스템 액세스 또는 윈도우 관리와 같은 기능을 위한 많은 추가 API를 제공합니다.

물론 데스크톱 응용 프로그램을 만들려면 그래픽 사용자 인터페이스를 만드는 방법이 필요합니다. 그렇죠?
표준 플래시는 이 작업에 적합하지 않았으므로 다른 SDK로 옮겨졌습니다: Flex(현재 Apache Flex).
또한 Flex는 XML 기반 마크 업 언어 (MXML이라 불리는)를 도입하여 사용자 인터페이스 레이아웃을 정의했습니다.

NOTE: Starling의 경우, Flex가 필요하지 않습니다. 단지 AIR SDK만 있으면 됩니다.

=== Flash 및 AIR의 현재 상태

AIR가 소개될 당시 AIR는 "RIA (Rich Internet Application)"라는 용어로 요약 된 추세의 일부였습니다. — 2000년대 후반에 유행했던 전문 용어입니다.
Adobe의 AIR와 Microsoft의 Silverlight (Sun의 JavaFX) 사이에는 치열한 경쟁이 있었습니다.
그러나 시간이 흐름에 따라 많은 것이 변했습니다.
결국 현재의 최후 승자는 엉뚱하게도 웹 기술로 애플리케이션을 구축 할 때 가장 많이 사용되는 기술 스택인 HTML5 / JavaScript입니다.
결국 어도비조차도 그 추세를 따라갔고 점점 더 많은 HTML5 지원을 자사 제품에 추가하고 있습니다.

TIP: 소프트웨어 개발에 관해서는 대중을 맹목적으로 뒤쫓는 함정에 빠지지 마십시오.
모든 문제에 대해 여러 가지 해결책이 있습니다.
그들 중 일부는 다른 사람들보다 더 적합합니다.
가장 편안하게 사용할 수있는 도구를 선택하십시오.
자신의 길을 벗어나 만들고자하는 소프트웨어에 집중할 수있게 해주는 도구가 그것입니다.

더 이상 "멋진 아이"가 아닐지라도 AIR / Flash 플랫폼은 여전히 소프트웨어를 만드는 매우 매력적인 플랫폼입니다.

* 레이디 가가 의상보다 빨리 변하는 인기 급상승 중인 HTML5의 조각난 세계와 비교하면 매우 성숙하고 사용하기 쉽습니다.
* 그것은 일상적인 개발에 필요한 모든 도구를 제공하는 광범위한 표준 라이브러리와 함께 제공됩니다.
* Flash 플러그인은 일반적인 웹 사이트의 쇠퇴를 분명히 보여 주지만 여전히 브라우저 게임의 표준입니다. 예를 들어 페이스북 게임의 대부분은 여전히 플래시로 제작됩니다.
* 특히 Starling과 Feathers와 결합되어 진정한 크로스 플랫폼 개발을 위한 가장 매끄러운 길 중 하나를 제공합니다 (모든 주요 데스크톱 및 모바일 플랫폼을 단일 코드 기반으로 타겟팅).

Starling에 대해 말하자면 ...이렇게 그려진 그림에 좀 들어 맞나요?
